wandb_version: 1

defaults:
  desc: null
  value:
  - mvsplat/encoder: dust_gs
  - mvsplat/decoder: splatting_cuda
silent:
  desc: null
  value: true
expname:
  desc: null
  value: dust2gs_4gpu
rootdir:
  desc: null
  value: ./
distributed:
  desc: null
  value: true
enable_tensorboard:
  desc: null
  value: true
enable_visdom:
  desc: null
  value: false
seed:
  desc: null
  value: 3407
pretrained:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
dist_url:
  desc: null
  value: env://
train_dataset:
  desc: null
  value: waymo
train_scenes:
  desc: null
  value:
  - 019
dataset_weights:
  desc: null
  value:
  - 1
eval_dataset:
  desc: null
  value: waymo
eval_scenes:
  desc: null
  value:
  - 019
num_source_views:
  desc: null
  value: 3
workers:
  desc: null
  value: 8
random_crop:
  desc: null
  value: false
outlier_ratio:
  desc: null
  value: 0.2
noise_level:
  desc: null
  value: 0.15
testskip:
  desc: null
  value: 8
ckpt_path:
  desc: null
  value: model_zoo/dust2gs.pth
no_load_opt:
  desc: null
  value: true
no_load_scheduler:
  desc: null
  value: true
use_pred_pose:
  desc: null
  value: false
use_kl_depth_loss:
  desc: null
  value: false
use_aux_loss:
  desc: null
  value: false
aux_cof:
  desc: null
  value: 1.0
optimizer:
  desc: null
  value: '{''lr'': 5e-05, ''warm_up_steps'': 500, ''lr_dust3r'': 1e-06, ''lr_dust3r_decay_steps'':
    2000}'
n_iters:
  desc: null
  value: 3000
n_validation:
  desc: null
  value: 1000
n_logging:
  desc: null
  value: 2
n_checkpoint:
  desc: null
  value: 500
visdom_port:
  desc: null
  value: 9000
llffhold:
  desc: null
  value: 8
det:
  desc: null
  value: false
lrate_feature:
  desc: null
  value: 0.001
lrate_gnt:
  desc: null
  value: 0.0005
single_net:
  desc: null
  value: true
trans_depth:
  desc: null
  value: 4
netwidth:
  desc: null
  value: 64
N_rand:
  desc: null
  value: 500
lrate_mlp:
  desc: null
  value: 0.0005
lrate_pose:
  desc: null
  value: 2.0e-05
lrate_decay_factor:
  desc: null
  value: 0.5
lrate_decay_steps:
  desc: null
  value: 2000
lrate_decay_pose_steps:
  desc: null
  value: 2000
coarse_only:
  desc: null
  value: true
rectify_inplane_rotation:
  desc: null
  value: false
coarse_feat_dim:
  desc: null
  value: 64
fine_feat_dim:
  desc: null
  value: 32
anti_alias_pooling:
  desc: null
  value: null
render_stride:
  desc: null
  value: 2
chunk_size:
  desc: null
  value: 2000
N_importance:
  desc: null
  value: 0
N_samples:
  desc: null
  value: 64
inv_uniform:
  desc: null
  value: true
white_bkgd:
  desc: null
  value: false
sample_mode:
  desc: null
  value: uniform
center_ratio:
  desc: null
  value: 0.8
feat_loss_scale:
  desc: null
  value: 10
mvsplat:
  desc: null
  value: '{''encoder'': {''name'': ''dust_gs'', ''opacity_mapping'': {''initial'':
    0.0, ''final'': 0.0, ''warm_up'': 500}, ''num_monocular_samples'': 32, ''num_surfaces'':
    1, ''predict_opacity'': False, ''near_disparity'': 3.0, ''gaussian_adapter'':
    {''gaussian_scale_min'': 0.5, ''gaussian_scale_max'': 15.0, ''sh_degree'': 4},
    ''shim_patch_size'': 4, ''downscale_factor'': 4, ''d_feature'': 128, ''epipolar_transformer'':
    {''self_attention'': {''patch_size'': 4, ''num_octaves'': 10, ''num_layers'':
    2, ''num_heads'': 4, ''d_token'': 128, ''d_dot'': 128, ''d_mlp'': 256}, ''num_octaves'':
    10, ''num_layers'': 2, ''num_heads'': 4, ''num_samples'': 32, ''num_context_views'':
    2, ''d_dot'': 128, ''d_mlp'': 256, ''downscale'': 4}, ''visualizer'': {''num_samples'':
    8, ''min_resolution'': 256, ''export_ply'': False}, ''apply_bounds_shim'': True,
    ''use_epipolar_transformer'': True, ''use_transmittance'': False, ''num_depth_candidates'':
    128, ''costvolume_unet_feat_dim'': 128, ''costvolume_unet_channel_mult'': [1,
    1, 1], ''costvolume_unet_attn_res'': [4], ''gaussians_per_pixel'': 1, ''depth_unet_feat_dim'':
    32, ''depth_unet_attn_res'': [16], ''depth_unet_channel_mult'': [1, 1, 1, 1, 1]},
    ''decoder'': {''name'': ''splatting_cuda''}}'
world_size:
  desc: null
  value: 4
gpu:
  desc: null
  value: 0
dist_backend:
  desc: null
  value: nccl
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714053784.803588
    t:
      1:
      - 1
      - 41
      - 55
      - 79
      2:
      - 1
      - 41
      - 55
      - 79
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
