### Model Config
defaults:
  - mvsplat/encoder: dust_gs
  - mvsplat/decoder: splatting_cuda
silent: True

### INPUT
expname : test
rootdir : ./
distributed : False
enable_tensorboard : True
enable_visdom : False
seed : 3407
pretrained : False
local_rank : 0
dist_url: env://

## dataset
# train_dataset : llff_test
# train_scenes : ['room']
# dataset_weights : [1]
# eval_dataset : llff_test
# eval_scenes : ['room']
train_dataset : waymo
train_scenes : ['019']
dataset_weights : [1]
eval_dataset : waymo
eval_scenes : ['019']

num_source_views : 2
workers : 8

random_crop : False
outlier_ratio : 0.2
noise_level : 0.15
testskip : 8

### Pretrain
ckpt_path: None
no_load_opt: True
no_load_scheduler: True

### TRAINING
use_pred_pose: False
use_kl_depth_loss: False
use_aux_loss: False
aux_cof: 1.0

optimizer:
  lr: 0.00005
  warm_up_steps: 500
  lr_dust3r: 0.000001
  lr_dust3r_decay_steps: 2000

### CONSOLE AND TENSORBOARD
n_iters: 6000
n_validation : 1000
n_logging : 2
n_checkpoint : 2000
visdom_port : 9000

### evaluation options
llffhold : 8