name: dust_gs

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 500

num_monocular_samples: 32
num_surfaces: 1
predict_opacity: false
near_disparity: 3.0

gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 4
shim_patch_size: 4
downscale_factor: 4

d_feature: 128

epipolar_transformer:
  self_attention:
    patch_size: 4
    num_octaves: 10
    num_layers: 2
    num_heads: 4
    d_token: 128
    d_dot: 128
    d_mlp: 256
  num_octaves: 10
  num_layers: 2
  num_heads: 4
  num_samples: 32
  num_context_views: 2
  d_dot: 128
  d_mlp: 256
  downscale: 4

visualizer:
  num_samples: 8
  min_resolution: 256
  export_ply: false

apply_bounds_shim: true

# Use this to ablate the epipolar transformer.
use_epipolar_transformer: true

use_transmittance: false



num_depth_candidates: 128
costvolume_unet_feat_dim: 128
costvolume_unet_channel_mult: [1,1,1]
costvolume_unet_attn_res: [4]
gaussians_per_pixel: 1
depth_unet_feat_dim: 32
depth_unet_attn_res: [16]
depth_unet_channel_mult: [1,1,1,1,1]

# below are ablation settings, keep them as false for default model
wo_depth_refine: false         # Table 3: base
wo_cost_volume: false          # Table 3: w/o cost volume
wo_backbone_cross_attn: false  # Table 3: w/o cross-view attention
wo_cost_volume_refine: false   # Table 3: w/o U-Net
use_epipolar_trans: false      # Table B: w/ Epipolar Transformer